In [2]:
#Basic libraries needed to read the image file
#OpenCV is used to work with images whereas numpy is used to work with arrays as all image files are converted to that format
import cv2
import numpy as np

In [3]:
#Import your file using 'imread' and pass parameter 0:greyscale, 1:colorimage, -1:import unchanged image
greyimg=cv2.imread('apple.jpg',0)
colorimg=cv2.imread('apple.jpg',1)
unchangedimg=cv2.imread('apple.jpg',-1)
#print the array of image which is stored on a variable
print("The grey image is represented by: "+str(greyimg))
print("----------------------------------")
print("The color image is represented by: "+str(colorimg))
print("----------------------------------")
print("The unchanged image is represented by: "+str(unchangedimg))

The grey image is represented by: [[121 114 119 ... 156 156 158]
 [117 109 112 ... 169 171 173]
 [112 106 110 ... 165 167 169]
 ...
 [140 142 145 ... 123 125 127]
 [134 136 137 ... 126 127 127]
 [140 140 140 ... 139 136 134]]
----------------------------------
The color image is represented by: [[[ 91 126 122]
  [ 84 119 115]
  [ 87 124 120]
  ...
  [103 168 153]
  [103 168 153]
  [105 170 155]]

 [[ 87 122 118]
  [ 77 114 110]
  [ 80 117 113]
  ...
  [114 181 166]
  [116 183 168]
  [118 186 169]]

 [[ 82 117 113]
  [ 74 111 107]
  [ 78 115 111]
  ...
  [107 178 161]
  [109 180 163]
  [111 182 165]]

 ...

 [[113 157 116]
  [115 160 117]
  [120 163 120]
  ...
  [109 139  98]
  [111 141  98]
  [111 144 100]]

 [[107 151 112]
  [109 153 112]
  [112 155 112]
  ...
  [112 143  98]
  [113 144  99]
  [111 144  99]]

 [[113 157 118]
  [113 157 118]
  [115 157 116]
  ...
  [125 156 111]
  [122 154 107]
  [118 152 105]]]
----------------------------------
The unchanged image is represented by: 

In [4]:
#print the image stored using 'imshow' parameter where 'image' refers to the name of the window and reference variable passed
cv2.imshow('image',greyimg)
cv2.imshow('image1',colorimg)
cv2.imshow('image2',unchangedimg)
while(True):
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
#waitkey is used to hold the image on a window for 5s
cv2.imwrite('greyimg.jpg',greyimg)

True